site_name: Projeto GIMP
site_description: Trabalho de Qualidade de Software para avaliação do GIMP

nav:
  - Sobre o projeto: index.md
  - Quem é Karen Jones: karenjones.md
  - Fase 1: 
    - Introdução: fase1/fase1.md
    - Propósito: fase1/1-proposito.md
    - Requisitantes: fase1/2-requistantes.md
    - Descrição: fase1/3-descricao.md
    - Justificativa: fase1/4-justificativa.md
    - Modelo: fase1/5-modelo.md

# Configuração do tema Material
theme:
  name: material
  language: pt-BR

  # Recursos de navegação e usabilidade
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  # Paleta de cores e temas
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/weather-night
        name: Mudar para modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-6
        name: Usar preferência do sistema
