site_name: Projeto GIMP
site_description: Trabalho de Qualidade de Software para avaliação do GIMP
repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-2_T02_Karen_Jones

nav:
  - Sobre o projeto: index.md
  - Quem é Karen Jones: karenjones.md
  - Fase 1: 
    - Introdução: fase1/fase1.md
    - Propósito: fase1/1-proposito.md
    - Requisitantes: fase1/2-requistantes.md
    - Descrição: fase1/3-descricao.md
    - Justificativa: fase1/4-justificativa.md
    - Modelo: fase1/5-modelo.md
    - Tabela de Contribuição: fase1/6-tabela de contribuição.md
# Configuração do tema Material
theme:
  name: material
  language: pt-BR

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  # Paleta de cores estilo GIMP
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro

extra_css:
  - css/custom.css
